// ... existing code ...
// This file is generated by `flutterfire configure`. Placeholder for illustration.
// Replace this with the actual generated file after running the CLI.
class DefaultFirebaseOptions {
  static const firebaseConfig = {
    "apiKey": "YOUR_API_KEY",
    "authDomain": "YOUR_AUTH_DOMAIN",
    "projectId": "YOUR_PROJECT_ID",
    "storageBucket": "YOUR_STORAGE_BUCKET",
    "messagingSenderId": "YOUR_SENDER_ID",
    "appId": "YOUR_APP_ID",
  };
}
// ... existing code ...